config/routes.rb
ItInTheD::Application.routes.draw do


  resources :testimonials

  resources :resources

  resources :events

  resources :faq

  resources :org_types

  resources :about_us

  resources :students

  resources :organizations
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout'}


  resources :contact_us

  resources :community


  resources :inquiries, :only => [:contact_us, :create] do
  get 'thank_you', :on => :collection
  end

  
  match '/search' => 'search#index', :as => :search
  match '/events/checkin/:id' => 'events#checkin', :as => :events_checkin
  match '/testimonials' => 'testimonials#show'
  match '/users/show/:id' => 'users#show'
  match '/people' => 'users#index', :as => :people
  match '/people/show/:id' => 'users#show', :as => :show_people
  match '/people/edit/:id' => 'users#edit', :as => :edit_people
  
  resources :users, :except => [:index, :show, :edit]
  
  get '/something/:youtube_user' => "utube#index"
  root :to => 'home#index'












  match ':controller(/:action(/:id))(.:format)'
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :local, :time, :title
  has_and_belongs_to_many :users #:dependent => :destroy
  #validates :title, :presence => true, :length => { :maximum => 50 }
  #validates :user_id, :presence => true

  #default_scope :order => 'events.created_at DESC'
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

    def checkin
      @event = Event.find(params[:id])
      @event.users << current_user
      redirect_to events_path
    end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event,:html => {:class => "form-horizontal", :multipart => true}) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :localtion %><br />
    <%= f.text_field :local %>
  </div>
  <div class="actions">
    <%= f.submit ' Submit ', :class=> "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Time</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.time %></td>
    <td><%= event.local %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete %></td>
    <td><a class="btn btn-primary btn-small"<%= link_to 'Checkin', events_checkin_path(event) %></a></td>

  </tr>
<% end %>
</table>

<br />

<a class="btn btn-primary btn-large" <%= link_to 'New Event', new_event_path %> </a>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Time:</b>
  <%= @event.time %>
</p>

<p>
  <b>Location:</b>
  <%= @event.local %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>