config/routes.rb
ItInTheD::Application.routes.draw do


  resources :testimonials

  resources :resources

  resources :events

  resources :faq

  resources :org_types

  resources :about_us

  resources :students

  resources :organizations
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout'}


  resources :contact_us

  resources :community


  resources :inquiries, :only => [:contact_us, :create] do
  get 'thank_you', :on => :collection
  end

  
  match '/search' => 'search#index', :as => :search
  match '/events/checkin/:id' => 'events#checkin', :as => :events_checkin
  match '/testimonials' => 'testimonials#show'
  match '/users/show/:id' => 'users#show'
  match '/people' => 'users#index', :as => :people
  match '/people/show/:id' => 'users#show', :as => :show_people
  match '/people/edit/:id' => 'users#edit', :as => :edit_people
  
  resources :users, :except => [:index, :show, :edit]
  
  get '/something/:youtube_user' => "utube#index"
  root :to => 'home#index'












  match ':controller(/:action(/:id))(.:format)'
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :local, :time, :title
  has_and_belongs_to_many :users #:dependent => :destroy
  #validates :title, :presence => true, :length => { :maximum => 50 }
  #validates :user_id, :presence => true

  #default_scope :order => 'events.created_at DESC'
end

app/models/inquiry.rb
class Inquiry
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActionView::Helpers::TextHelper
  
  attr_accessor :name, :email, :message, :nickname
  
  validates :name, 
            :presence => true
  
  validates :email,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
  
  validates :message,
            :length => { :minimum => 10, :maximum => 1000 }
            
  validates :nickname, 
            :format => { :with => /^$/ }
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def deliver
    return false unless valid?
    Pony.mail({
      :from => %("#{name}" <#{email}>),
      :reply_to => email,
      :subject => "ITinTheD inquiry",
      :body => message,
      :html_body => simple_format(message)
    })
  end
      
  def persisted?
    false
  end
end

app/models/oldyoutube.rb
class Youtube

  def self.get_videos(user)
    result = HTTParty.get("https://gdata.youtube.com/feeds/api/users/#{user}/uploads?alt=json")
    json = ActiveSupport::JSON.decode(result.body)

    array_of_videos = []

    json["feed"]["entry"].each do |video|

      #How to parse and regex the youtube video key
      key = video["id"]["$t"].split("/").last

      #Load keys into the array we defined earlier
      array_of_videos << key
    end

    return array_of_videos
  end
end

app/models/org_type.rb
class OrgType < ActiveRecord::Base
  attr_accessible :name, :icon
  has_many :organizations 
end

app/models/organization.rb
class Organization < ActiveRecord::Base

  attr_accessible :address, :city, :lat, :long, :name, :org_url, :web_link, :zip, :keyword_list, :org_type_id, :logo, :org_num_students_employ, :org_start_year, :org_annual_sales, :org_optional_stat_a, :org_job, :org_phone, :org_state, :description, :org_type, :socials_attributes

  has_attached_file :logo,
                    :url => '/system/:class/:attachment/:id/:style/:filename'
  acts_as_taggable
  acts_as_taggable_on :keywords
  has_many :socials
  accepts_nested_attributes_for :socials
  belongs_to :org_type
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  attr_accessible :resource_count, :attachment, :resource_title, :resource_url, :resource_type

  has_attached_file :attachment

  validates :resource_type, :resource_title, :presence => true
  validate :must_be_url_or_attachment

  private
  	def must_be_url_or_attachment
  		if self.attachment.blank? and self.resource_url.blank?
  			errors.add(:resource, "The resource must have a URL or an attachment.")
        return false
        elsif !self.attachment.blank? and !self.resource_url.blank?
        	errors.add(:resource, "Cannot have both a URL and an attachment.")
        return false
    else
        return true
    end
  end
end

app/models/social.rb
class Social < ActiveRecord::Base
  belongs_to :organization
  attr_accessible :soc_type, :soc_url
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  attr_accessible :content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :location, :city, :state, :zip, :telephone, :summary, :avatar, :header, :resume, :user_type

 # def self.find_for_database_authentication(conditions={})
 #   self.where("username = ?", conditions[:email]).limit(1).first ||
 #   self.where("email = ?", conditions[:email]).limit(1).first
 # end

  has_attached_file :avatar,
                    :url => '/system/:class/:attachment/:id/:style/:filename'

end

app/models/youtitle.rb
class Youtitle
  def self.get_titles(user)
    result = HTTParty.get("https://gdata.youtube.com/feeds/api/users/#{user}/uploads?alt=json")
    json = ActiveSupport::JSON.decode(result.body)

    array_of_titles = []
    json["feed"]["entry"].each do |video|
      key =  video["title"]["$t"]
      
      #How to parse and regex the youtube title key
      #key = video["id"]["$t"].split("/")

      #Load keys into the array we defined earlier
      array_of_titles << key
    end
    #raise array_of_titles.inspect
    return array_of_titles
  end
end

app/models/youtube.rb
require 'video_info'

class Youtube

  def self.get_players(user)
    result = HTTParty.get("https://gdata.youtube.com/feeds/api/users/#{user}/uploads?alt=json")
    json = ActiveSupport::JSON.decode(result.body)

      array = []

      json["feed"]["entry"].each do |player|

        #How to parse and regex the youtube video key
        key = player["id"]["$t"].split("/").last

        #Use gem to access hash attibutes
        video = VideoInfo.get("http://www.youtube.com/watch?v=#{key}")
        iframe_src = "http://www.youtube.com/embed/#{key}?wmode=opaque;rel=0;showinfo=0;controls=0;autoplay=0"
        #Load titles and players into and r
        hash = {:title => video.title, :iframe_src => iframe_src}

        array << hash
    end

    return array
  end
end

app/models/youtubeold.rb
class Youtube
  def self.get_videos(user)
    result = HTTParty.get("https://gdata.youtube.com/feeds/api/users/#{user}/uploads?alt=json")
    json = ActiveSupport::JSON.decode(result.body)

    array_of_videos = []

    json["feed"]["entry"].each do |video|

      #How to parse and regex the youtube video key
      key = video["id"]["$t"].split("/").last

      #Load keys into the array we defined earlier
      array_of_videos << key
    end

    return array_of_videos
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML

    <div class="alert alert-error">
      <h4>#{sentence}</h4>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/org_types_helper.rb
module OrgTypesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/utube_helper.rb
module UtubeHelper
end

app/helpers/youtitle_helper.rb
module YoutitleHelper
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
<p>&nbsp;</p>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="content_title"><p>Resource</p></div>
    <div class="myboxinner">
      <div class="row-fluid">
        <div class="span4">
          <div class="field" style="float:center">
            <%= f.label "Title" %>
            <%= f.text_field :resource_title %>
          </div>
        </div>
        <div class="span4">
          <div class="field" style="float:center">
            <%= f.label "URL" %>
            <%= f.url_field :resource_url, :value => "http://" %>
          </div>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span4">
          <div class="field" style="float:center">
            <%= f.label "File" %>
            <%= f.file_field :attachment %>
          </div>
        </div>
        <div class="span4">
          <div class="field" style="float:center">
            <%= f.label "Type" %>
            <%= f.select(:resource_type,[["Notes"], ["Images"], ["Training"], ["Links"], ["Tools"], ["Help"]], :prompt => 'Select a type') %>
          </div>
        </div>
      </div>
    </div>


  <div class="actions">
    <%= f.submit ' Submit ', :class=> "btn btn-primary" %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<%= render 'form' %>

<div id="linkcontainer1r">
<%= link_to 'Show', @resource %> |
</div>
<div id="linkcontainer11r">
<%= link_to 'Back', resources_path %>
</div>

app/views/resources/index.html.erb
<div id="resources_container">
<h3>Resources</h3>



<div class='row' style="margin-left:0px">
  <div id="resource_container" style="margin-left:0px", class="span5">
    <div class="content_title"><p> Notes from Session </p> </div>
    <section></br>
      <table class="table table-striped">
        <tr>
          <th>Title</th>
          <th>URL or Attachment</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @notes.each do |notes| %>
          <tr>
            <td><%= notes.resource_title %></td>
            <% if !notes.resource_url.blank? %>
            <td><%= link_to truncate(notes.resource_url, :ommision => "...", :length => 20), notes.resource_url %></td>
            <% end %>
            <% if !notes.attachment_file_size.blank? %>
            <td><%= link_to truncate(notes.attachment_file_name, :ommision => "...", :length => 20), notes.attachment.url %></td>
            <% end %>
            <td><%= notes.resource_count %></td>
            <td><%= link_to 'Show', notes %></td>
            <td><%= link_to 'Edit', edit_resource_path(notes) %></td>
            <td><%= link_to 'Destroy', notes, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
        <% end %>
      </table>
    </section>
  </div>

  <div id="resource1_container"  style="margin-left:40px", class="span5">
    <div class="content_title"><p> Images </p> </div>
    <section></br>
     <table class="table table-striped">
        <tr>
          <th>Title</th>
          <th>URL or Attachment</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @images.each do |images| %>
          <tr>
            <td><%= images.resource_title %></td>
            <% if !images.resource_url.blank? %>
            <td><%= link_to truncate(images.resource_url, :ommision => "...", :length => 20), images.resource_url %></td>
            <% end %>
            <% if !images.attachment_file_size.blank? %>
            <td><%= link_to truncate(images.attachment_file_name, :ommision => "...", :length => 20), images.attachment.url %></td>
            <% end %>
            <td><%= images.resource_count %></td>
            <td><%= link_to 'Show', images %></td>
            <td><%= link_to 'Edit', edit_resource_path(images) %></td>
            <td><%= link_to 'Destroy', images, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
        <% end %>
      </table>
    </section>
  </div>
</div>

<div class='row' style="margin-left:0px">
  <div id="resource2_container" style="margin-left:0px", class="span5">
    <div class="content_title"><p> Training </p> </div>
    <section></br>
      <table class="table table-striped">
        <tr>
          <th>Title</th>
          <th>URL or Attachment</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @training.each do |training| %>
          <tr>
            <td><%= training.resource_title %></td>
            <% if !training.resource_url.blank? %>
            <td><%= link_to truncate(training.resource_url, :ommision => "...", :length => 20), training.resource_url %></td>
            <% end %>
            <% if !training.attachment_file_size.blank? %>
            <td><%= link_to truncate(training.attachment_file_name, :ommision => "...", :length => 20), training.attachment.url %></td>
            <% end %>
            <td><%= training.resource_count %></td>
            <td><%= link_to 'Show', training %></td>
            <td><%= link_to 'Edit', edit_resource_path(training) %></td>
            <td><%= link_to 'Destroy', training, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
        <% end %>
      </table>
    </section>
  </div>

  <div id="resource3_container"  style="margin-left:40px", class="span5">
    <div class="content_title"><p> Links </p> </div>
    <section></br>
      <table class="table table-striped">
        <tr>
          <th>Title</th>
          <th>URL or Attachment</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @links.each do |links| %>
          <tr>
            <td><%= links.resource_title %></td>
            <% if !links.resource_url.blank? %>
            <td><%= link_to truncate(links.resource_url, :ommision => "...", :length => 20), links.resource_url %></td>
            <% end %>
            <% if !links.attachment_file_size.blank? %>
            <td><%= link_to truncate(links.attachment_file_name, :ommision => "...", :length => 20), links.attachment.url %></td>
            <% end %>
            <td><%= links.resource_count %></td>
            <td><%= link_to 'Show', links %></td>
            <td><%= link_to 'Edit', edit_resource_path(links) %></td>
            <td><%= link_to 'Destroy', links, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
        <% end %>
      </table>
    </section>
  </div>
</div>
<div class='row' style="margin-left:0px">
  <div id="resource4_container" style="margin-left:0px", class="span5">
    <div class="content_title"><p> Tools </p> </div>
    <section></br>
      <table class="table table-striped">
        <tr>
          <th>Title</th>
          <th>URL or Attachment</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @tools.each do |tools| %>
          <tr>
            <td><%= tools.resource_title %></td>
            <% if !tools.resource_url.blank? %>
            <td><%= link_to truncate(tools.resource_url, :ommision => "...", :length => 20), tools.resource_url %></td>
            <% end %>
            <% if !tools.attachment_file_size.blank? %>
            <td><%= link_to truncate(tools.attachment_file_name, :ommision => "...", :length => 20), tools.attachment.url %></td>
            <% end %>
            <td><%= tools.resource_count %></td>
            <td><%= link_to 'Show', tools %></td>
            <td><%= link_to 'Edit', edit_resource_path(tools) %></td>
            <td><%= link_to 'Destroy', tools, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
        <% end %>
      </table>
    </section>
  </div>

  <div id="resource5_container"  style="margin-left:40px", class="span5">
    <div class="content_title"><p> Help </p> </div>
    <section></br>
     <table class="table table-striped">
        <tr>
          <th>Title</th>
          <th>URL or Attachment</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @help.each do |help| %>
          <tr>
            <td><%= help.resource_title %></td>
            <% if !help.resource_url.blank? %>
            <td><%= link_to truncate(help.resource_url, :ommision => "...", :length => 20), help.resource_url %></td>
            <% end %>
            <% if !help.attachment_file_size.blank? %>
            <td><%= link_to truncate(help.attachment_file_name, :ommision => "...", :length => 20), help.attachment.url %></td>
            <% end %>
            <td><%= help.resource_count %></td>
            <td><%= link_to 'Show', help %></td>
            <td><%= link_to 'Edit', edit_resource_path(help) %></td>
            <td><%= link_to 'Destroy', help, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
        <% end %>
      </table>
    </section>
  </div>
</div>
<br />

<div class="actions">
  <a class="btn btn-primary" <%= link_to 'New Resource', new_resource_path %> </a>
</div>
</div>

app/views/resources/new.html.erb
<%= render 'form' %>

<div id="linkcontainer2r">
<%= link_to 'Back', resources_path %>
</div>

app/views/resources/show.html.erb
<h3><%= notice %></h3>

<p>
  <b>Title:</b>
  <%= @resource.resource_title %>
</p>
<p>
	<b>Type:</b>
	<%= @resource.resource_type %>
</p>
<% if !@resource.resource_url.blank? %>
<p>
  <b>URL:</b>
  <%= link_to @resource.resource_url, @resource.resource_url %>
</p>
<% end %>
<% if !@resource.attachment_file_size.blank? %>
<p>
  <b>File:</b>
      <td><%= link_to @resource.attachment_file_name, @resource.attachment.url %></td>
</p>
<% end %>

<% if current_user %>
  <% if current_user.user_type == "admin" %>
<div id="linkcontainer3r">
<%= link_to 'Edit', edit_resource_path(@resource) %> |
</div>
  <% end %>
<% end %>
<div id="linkcontainer33r">
  <%= link_to 'Back', resources_path %>
</div>