config/routes.rb
ItInTheD::Application.routes.draw do


  resources :testimonials

  resources :resources

  resources :events

  resources :faq

  resources :org_types

  resources :about_us

  resources :students

  resources :organizations
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout'}


  resources :contact_us

  resources :community


  resources :inquiries, :only => [:contact_us, :create] do
  get 'thank_you', :on => :collection
  end

  
  match '/search' => 'search#index', :as => :search
  match '/events/checkin/:id' => 'events#checkin', :as => :events_checkin
  match '/testimonials' => 'testimonials#show'
  match '/users/show/:id' => 'users#show'
  match '/people' => 'users#index', :as => :people
  match '/people/show/:id' => 'users#show', :as => :show_people
  match '/people/edit/:id' => 'users#edit', :as => :edit_people
  
  resources :users, :except => [:index, :show, :edit]
  
  get '/something/:youtube_user' => "utube#index"
  root :to => 'home#index'












  match ':controller(/:action(/:id))(.:format)'
end

app/models/organization.rb
class Organization < ActiveRecord::Base

  attr_accessible :address, :city, :lat, :long, :name, :org_url, :web_link, :zip, :keyword_list, :org_type_id, :logo, :org_num_students_employ, :org_start_year, :org_annual_sales, :org_optional_stat_a, :org_job, :org_phone, :org_state, :description, :org_type, :socials_attributes

  has_attached_file :logo,
                    :url => '/system/:class/:attachment/:id/:style/:filename'
  acts_as_taggable
  acts_as_taggable_on :keywords
  has_many :socials
  accepts_nested_attributes_for :socials
  belongs_to :org_type
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])
    @socials = @organization.socials

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new
    @social = @organization.socials.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])
    respond_to do |format|
      if @organization.save
        
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])
    
    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end
end


app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization,:html => {:class => "form-horizontal", :multipart => true}) do |f| %>

<p>&nbsp;</p>
<div class="content_title"><p>Sponsor</p></div>
  <div class="myboxinner">
<p class="clear">&nbsp;</p>
<% if @organization.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>
    <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="row-fluid">
  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "Name" %>
      </label>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
  </div>

  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "Year Established" %>
      </label>
      <div class="controls">
        <%= f.text_field :org_start_year %>
      </div>
    </div>
  </div>

  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "Phone" %>
      </label>
      <div class="controls">
        <%= f.text_field :org_phone, :value => 'ex.(734) 555-1234' %>
      </div>
    </div>
  </div>
</div> 

<div class="row-fluid">
  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "Address" %>
      </label>
      <div class="controls">
        <%= f.text_field :address %>
      </div>
    </div>
  </div>
 
  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "City" %>
      </label>
      <div class="controls">
        <%= f.text_field :city %>
      </div>
    </div>
  </div>

  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "State" %>
      </label>
        <div class="controls">
          <%= f.select(:org_state,[["Alabama       "],["Alaska        "],["Arizona       "],
                                   ["Arkansas      "],["California    "],["Colorado      "],
                                   ["Connecticut   "],["Delaware      "],["Florida       "],
                                   ["Georgia       "],["Hawaii        "],["Idaho         "],
                                   ["Illinois      "],["Indiana       "],["Iowa          "],
                                   ["Kansas        "],["Kentucky      "],["Louisiana     "],
                                   ["Maine         "],["Maryland      "],["Massachusetts "],
                                   ["Michigan      "],["Minnesota     "],["Mississippi   "],
                                   ["Missouri      "],["Montana       "],["Nebraska      "],
                                   ["Nevada        "],["New Hampshire "],["New Jersey    "],
                                   ["New Mexico    "],["New York      "],["North Carolina"],
                                   ["North Dakota  "],["Ohio          "],["Oklahoma      "],
                                   ["Oregon        "],["Pennsylvania  "],["Puerto Rico   "],
                                   ["Rhode Island  "],["South Carolina"],["South Dakota  "],
                                   ["Tennessee     "],["Texas         "],["Utah          "],
                                   ["Vermont       "],["Virginia      "],["Washington    "],
                                   ["Washington DC "],["West Virginia "],["Wisconsin     "],
                                   ["Wyoming       "]],
                                  :prompt => 'Select a state') %>

        </div>
      </div>
    </div>
  </div>
<div class="row-fluid">
  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "Zip" %>
      </label>
      <div class="controls">
        <%= f.text_field :zip %>
      </div>
    </div>
  </div>
 
  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "URL" %>
      </label>
      <div class="controls">
        <%= f.url_field :org_url, :value => "http://" %>
      </div>
    </div>
  </div>

  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "Type" %>
      </label>
      <div class="controls">
        <%= f.select(:keyword_list, [["School"], ["Company"]], :prompt => 'Select a type') %>
      </div>
    </div>
  </div>
</div>

<div class="row-fluid">
  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "# In Organization"%>
      </label>
      <div class="controls">
        <%= f.text_field :org_num_students_employ %>
      </div>
    </div>
  </div>
  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "Annual Income" %>
      </label>
      <div class="controls">
        <%= f.text_field :org_annual_sales %>
      </div>
    </div>
  </div>
  <div class="span4">
    <div class="control-group">
      <label class="left">
        <%= f.label "Logo" %>
      </label>
        <div class="controls">
          <%= f.file_field :logo %>
        </div>
      </div>
    </div>
  </div> 

<div class="row-fluid">
  <div class="span12">
    <div class="control-group">
      <label class="left">
        <%= f.label "Description" %>
      </label>
      <div class="controls">
        <%= f.text_area :description , :style=>"width:475px; height:50px" %>
      </div>
    </div>
  </div>
</div> 

</div>

<br><br>
<%= f.fields_for :socials do |builder| %>
<%= render 'social', :f => builder %>
<% end %>

<div class="actions">
  <%= f.submit ' Submit ', :class=> "btn btn-primary" %>
</div>
<% end %>


app/views/organizations/_soc_url.html.erb
<p> <%=socials.soc_url%> </p>

app/views/organizations/_social.html.erb
<div class="content_title"><p>Socials (optional)</p></div>
  <div class="myboxinner">
    <div class="row-fluid" id="extraspace">
      <div class="span4">
        <div class="control-group">
          <label class="left">
          <%=f.label "Facebook Profile URL" %>
          </label>
            <div class="controls">
            <%= f.text_field :soc_url, :value => "http://facebook.com/" %>
            </div>
        </div>
      </div>
      <div class="span4">
        <div class="control-group">
          <label class="left">
          <%=f.label "Twitter Profile URL" %>
           </label>

            <div class="controls">
            <%= f.url_field :soc_url, :value => "http://twitter.com/" %>
            </div>
        </div>
      </div>
      <div class="span4">
        <div class="control-group">
          <label class="left">
          <%=f.label "Google+ Profile URL" %>
          </label>

            <div class="controls">
            <%= f.text_field :soc_url, :value => "https://plus.google.com"  %>
            </div>
        </div>
      </div>
    </div> 

   <div class="row-fluid" id="extraspace">
      <div class="span4">
        <div class="control-group">
          <label class="left">
          <%=f.label "LinkedIn Profile URL" %>
          </label>

            <div class="controls">
             <%= f.text_field :soc_url, :value => "http://linkedin.com/" %>
            </div>
        </div>
      </div>
      <div class="span4">
        <div class="control-group">
          <label class="left">
         <%=f.label "MySpace Profile URL" %>
          </label>

            <div class="controls">
            <%= f.text_field :soc_url, :value => "http://myspace.com/" %>
            </div>
        </div>
      </div>
      <div class="span4">
        <div class="control-group">
        <label class="left">
        <%= f.label "Other Profile URL" %>
        </label>
          <div class="controls">
            <%= f.text_field :soc_url, :value => "http://" %>
            </div>
        </div>
      </div>
    </div> 
</div>

app/views/organizations/edit.html.erb
<%= render 'form' %>

<div id="linkcontainer1o">
<%= link_to 'Show', @organization %> |
</div>
<div id="linkcontainer11o">
<%= link_to 'Back', organizations_path %>
</div>


app/views/organizations/index.html.erb
<div id="resources_container">
<h3>Sponsors</h3>  
 

<table  class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Year Established</th>
    <th>Phone</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>URL</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organizations.each do |organization| %>
  <tr>
    <td><%= organization.name %></td>
    <td><%= organization.org_start_year %></td>
    <td><%= organization.org_phone %></td>
    <td><%= organization.address %></td>
    <td><%= organization.city %></td>
    <td><%= organization.org_state %></td>
    <td><%= organization.zip %></td>
    <td id="linksponsor"><%= link_to organization.org_url, organization.org_url %></td>
    <td><%= organization.keyword_list %></td>
    <td id="showsponsor"><%= link_to 'Show', organization %></td>
    <td id="editsponsor"><%= link_to 'Edit', edit_organization_path(organization) %></td>
    <td id="destroysponsor"><%= link_to 'Destroy', organization, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<div class="actions">
    <a class="btn btn-primary" <%= link_to 'New Sponsor', new_organization_path %> </a>
</div>

app/views/organizations/new.html.erb
<%= render 'form' %>

<div id="linkcontainer2o">
<%= link_to 'Back', organizations_path %>
</div>

app/views/organizations/show.html.erb


<div class="row-fluid">
  <div class="span3" style="background-color:white">
<!--Sidebar text content-->
    <div class="content_title"><p>At a glance:</p></div>

        <section>
          <div id="org_logo">
            <a href=<%= @organization.org_url %> >
              <!--<%= image_tag @organization.logo.url%>
              <%= image_tag @organization.logo.url(:medium) %>-->
              <div class="image-size">
                <%= image_tag @organization.logo.url %>
              </div>
            </a>
          </div>
        </section>
        <section id="box_padding">
          <p class="clear">Year established: <%= @organization.org_start_year %></p>  
          <p>Number in Organization: <%= @organization.org_num_students_employ %></p>
          <p>Annual Income: $<%= @organization.org_annual_sales %></p>
        </section>
        <div>
          <!--Space holder for additional content content-->
          <p>&nbsp;<br />&nbsp;<br />&nbsp;</p>
        </div>

  </div>

  <div class="span9" style="background-color:white">
    <div class="content_title"></div>

      <br/>
      <!--Body content-->
      <h2 id="no_topmarg"><%= @organization.name %></h2>
      <p><%= @organization.address %></p>
      <p><%= @organization.city %>, <%= @organization.org_state %> <%= @organization.zip %></p> 
      <p><%= @organization.org_phone %></p>
      <p><%= link_to @organization.org_url, @organization.org_url %></p>
      <p><%= @organization.keyword_list %></p>                    
      <!--Body 2 content-->
      <p><strong>Summary</strong></p>
      <p style="word-wrap:break-word; width:90ex"><%= @organization.description %>
      </p>
      <!--Body 3 content-->
      <p><strong>Social Networks</strong><p>
        <%= render :partial => 'organizations/soc_url', :collection => @socials, :as => :socials  %>

  </div>
</div>





<% if current_user %>
  <% if current_user.user_type == "admin" %>
<div id="linkcontainer3o">
<%= link_to 'Edit', edit_organization_path(@organization) %> |
</div>
  <% end %>
<% end %>
<div id="linkcontainer33o">
<%= link_to 'Back', organizations_path %>
</div>




<!--
<%#= image_tag @organization.logo.url %>
<%#= image_tag @organization.logo.url(:medium) %>
<%#= image_tag @organization.logo.url(:thumb) %>
-->

