config/routes.rb
ItInTheD::Application.routes.draw do


  resources :testimonials

  resources :resources

  resources :events

  resources :faq

  resources :org_types

  resources :about_us

  resources :students

  resources :organizations
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout'}


  resources :contact_us

  resources :community


  resources :inquiries, :only => [:contact_us, :create] do
  get 'thank_you', :on => :collection
  end

  
  match '/search' => 'search#index', :as => :search
  match '/events/checkin/:id' => 'events#checkin', :as => :events_checkin
  match '/testimonials' => 'testimonials#show'
  match '/users/show/:id' => 'users#show'
  match '/people' => 'users#index', :as => :people
  match '/people/show/:id' => 'users#show', :as => :show_people
  match '/people/edit/:id' => 'users#edit', :as => :edit_people
  
  resources :users, :except => [:index, :show, :edit]
  
  get '/something/:youtube_user' => "utube#index"
  root :to => 'home#index'












  match ':controller(/:action(/:id))(.:format)'
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  attr_accessible :content
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  def index
    @testimonials = Youtube.get_players("UC3sD2LbS9knGoDeANxiUbFw")
  end
end

#class TestimonialsController < ApplicationController
# GET /testimonials
#  GET /testimonials.json
#  def index
#   @testimonials = Testimonial.all
 
#     respond_to do |format|
#     format.html # index.html.erb
#     format.json { render json: @testimonials }
#    end
# end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/new
  # GET /testimonials/new.json
#  def new
#    @testimonial = Testimonial.new

#    respond_to do |format|
#      format.html # new.html.erb
#      format.json { render json: @testimonial }
#    end
#  end

  # GET /testimonials/1/edit
#  def edit
#    @testimonial = Testimonial.find(params[:id])
# end

  # POST /testimonials
  # POST /testimonials.json
#  def create
#    @testimonial = Testimonial.new(params[:testimonial])

#   respond_to do |format|
#      if @testimonial.save
#        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
#        format.json { render json: @testimonial, status: :created, location: @testimonial }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
#      end
#   end
#  end

  # PUT /testimonials/1
  # PUT /testimonials/1.json
#  def update
#   @testimonial = Testimonial.find(params[:id])

#    respond_to do |format|
#      if @testimonial.update_attributes(params[:testimonial])
#        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
#        format.json { head :no_content }
#      else
#        format.html { render action: "edit" }
#        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
 # def destroy
 #   @testimonial = Testimonial.find(params[:id])
 #
#    respond_to do |format|
#      format.html { redirect_to testimonials_url }
#      format.json { head :no_content }
#    end
#  end
#end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= form_for(@testimonial) do |f| %>
  <% if @testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% @testimonial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<h3>TESTIMONIALS</h3>
          
<% @testimonials.each do |testimonial| %>

<div id="testimonial_container" class='span5' style="margin-left:10px">    
      <div class="content_title"> <p><%= testimonial[:title]%></p> </div>

        <section>
          <iframe width="470" height="315" src=<%=testimonial[:iframe_src]%> frameborder="4" allowfullscreen></iframe>
        </section>
  </div>
<% end %>

app/views/testimonials/new.html.erb
<h1>New testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @testimonial.content %>
</p>


<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>